### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by rj23495** [oracle/weblogic-monitoring-exporter#10]
Hey,

I deployed war file on my weblogic server and i am getting the following exception in logs 
Can you please explain why am i getting such error?

```
Caused By: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:145)
	at io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:141)
	at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:84)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:62)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:55)
	at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:247)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3679)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3649)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2433)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2281)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2259)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1691)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1651)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:270)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:348)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:333)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:54)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:640)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:406)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:346)


```

**Comment by rj23495** [comment]
```
---
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
    workManagerRuntimes:
      prefix: workmanager_
      key: applicationName
      values: [pendingRequests, completedRequests, stuckThreadCount]
    componentRuntimes:
      type: JDBCOracleDataSourceRuntime
      prefix: jdbc_oracle_
      key: name
      values: [activeConnectionsAverageCount, activeConnectionsCurrentCount, activeConnectionsHighCount, connectionsTotalCount, deploymentState, leakedConnectionCount, waitingForConnectionCurrentCount, waitingForConnectionFailureTotal, waitingForConnectionHighCount, waitingForConnectionSuccessTotal, waitingForConnectionTotal, waitSecondsHighCount]
- JVMRuntime:
    key: name
    prefix: jvm_
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]
- ThreadPoolRuntime:
    key: name
    prefix: threadpool_
    values: [executeThreadTotalCount, throughput, hoggingThreadCount, standbyThreadCount, executeThreads, executeThreadIdleCount]
```

**Comment by rj23495** [comment]
hey????did u go through the configuration once?

**Comment by russgold** [comment]
Sorry, trying to get to this. I haven’t forgotten. It looks fine. What version of WLS are you using?

**Comment by rj23495** [comment]
wls version is 12.2.1.2

**Comment by rj23495** [comment]
hey have you gone through the issue? its urgent...

**Comment by russgold** [comment]
I'd really like to spend more time on this, but we are in the middle of a release of another product. That means that it could be another week or two before I can really dive in.

**Comment by marinakog** [comment]
Hello @rj23495 

it looks like your configuration has errors:
ThreadPoolRuntime should be threadPoolRuntime , is it possible for you to try it with correct name for MBean and see if it makes difference? 
the best to check the Mbeans names and attributes to run something like that( please replace with your values of the host and port): http://slc13kef.us.oracle.com:8001/management/weblogic/latest/serverRuntime/threadPoolRuntime

Do you get any metrics back by hitting url ( please replace with your values of the host and port) : http://slc13kef.us.oracle.com:9101/wls-exporter/metrics

**Comment by marinakog** [comment]
with that correction I am able to get these values in my env:
workmanager_completed_requests{app="DemoApp",applicationName="DemoApp"} 0
workmanager_completed_requests{app="bea_wls_cluster_internal",applicationName="bea_wls_cluster_internal"} 0
workmanager_completed_requests{app="bea_wls_deployment_internal",applicationName="bea_wls_deployment_internal"} 70
workmanager_completed_requests{app="bea_wls_internal",applicationName="bea_wls_internal"} 0
workmanager_completed_requests{app="jms-internal-notran-adp",applicationName="jms-internal-notran-adp"} 0
workmanager_completed_requests{app="jms-internal-xa-adp",applicationName="jms-internal-xa-adp"} 0
workmanager_completed_requests{app="weblogic",applicationName="weblogic"} 1
workmanager_completed_requests{app="wls-management-services",applicationName="wls-management-services"} 0
workmanager_completed_requests{app="wlsExporter",applicationName="wlsExporter"} 11
workmanager_pending_requests{app="DemoApp",applicationName="DemoApp"} 0
workmanager_pending_requests{app="bea_wls_cluster_internal",applicationName="bea_wls_cluster_internal"} 0
workmanager_pending_requests{app="bea_wls_deployment_internal",applicationName="bea_wls_deployment_internal"} 0
workmanager_pending_requests{app="bea_wls_internal",applicationName="bea_wls_internal"} 0
workmanager_pending_requests{app="jms-internal-notran-adp",applicationName="jms-internal-notran-adp"} 0
workmanager_pending_requests{app="jms-internal-xa-adp",applicationName="jms-internal-xa-adp"} 0
workmanager_pending_requests{app="weblogic",applicationName="weblogic"} 0
workmanager_pending_requests{app="wls-management-services",applicationName="wls-management-services"} 0
workmanager_pending_requests{app="wlsExporter",applicationName="wlsExporter"} 1
workmanager_stuck_thread_count{app="DemoApp",applicationName="DemoApp"} 0
workmanager_stuck_thread_count{app="bea_wls_cluster_internal",applicationName="bea_wls_cluster_internal"} 0
workmanager_stuck_thread_count{app="bea_wls_deployment_internal",applicationName="bea_wls_deployment_internal"} 0
workmanager_stuck_thread_count{app="bea_wls_internal",applicationName="bea_wls_internal"} 0
workmanager_stuck_thread_count{app="jms-internal-notran-adp",applicationName="jms-internal-notran-adp"} 0
workmanager_stuck_thread_count{app="jms-internal-xa-adp",applicationName="jms-internal-xa-adp"} 0
workmanager_stuck_thread_count{app="weblogic",applicationName="weblogic"} 0
workmanager_stuck_thread_count{app="wls-management-services",applicationName="wls-management-services"} 0
workmanager_stuck_thread_count{app="wlsExporter",applicationName="wlsExporter"} 0
jvm_heap_free_current{name="ms1"} 313985496
jvm_heap_free_percent{name="ms1"} 63
jvm_heap_size_current{name="ms1"} 491782144
jvm_heap_size_max{name="ms1"} 491782144
jvm_process_cpu_load{name="ms1"} 0.004272940244827927
jvm_uptime{name="ms1"} 3212907
threadpool_execute_thread_idle_count{name="ThreadPoolRuntime"} 1
threadpool_execute_thread_total_count{name="ThreadPoolRuntime"} 14
threadpool_hogging_thread_count{name="ThreadPoolRuntime"} 1
threadpool_standby_thread_count{name="ThreadPoolRuntime"} 10
threadpool_throughput{name="ThreadPoolRuntime"} 5

**Comment by rj23495** [comment]
thanks!!!
I will try this configuration once.

**Comment by rj23495** [comment]
i tried the mentioned configuration but still it doesnt rectify the error.
---
metricsNameSnakeCase: true
queries:
- applicationRuntimes:
    key: name
    keyName: app
    componentRuntimes:
      type: WebAppComponentRuntime
      prefix: webapp_config_
      key: name
      values: [deploymentState, contextRoot, sourceInfo, openSessionsHighCount, openSessionsCurrentCount, sessionsOpenedTotalCount, sessionCookieMaxAgeSecs, sessionInvalidationIntervalSecs, sessionTimeoutSecs, singleThreadedServletPoolSize, sessionIDLength, servletReloadCheckSecs, jSPPageCheckSecs]
      servlets:
        prefix: weblogic_servlet_
        key: servletName
        values: [invocationTotalCount, reloadTotal, executionTimeAverage, poolMaxCapacity, executionTimeTotal, reloadTotalCount, executionTimeHigh, executionTimeLow]
    componentRuntimes:
      type: JDBCOracleDataSourceRuntime
      prefix: jdbc_oracle_
      key: name
      values: [activeConnectionsAverageCount, activeConnectionsCurrentCount, activeConnectionsHighCount, connectionsTotalCount, deploymentState, leakedConnectionCount, waitingForConnectionCurrentCount, waitingForConnectionFailureTotal, waitingForConnectionHighCount, waitingForConnectionSuccessTotal, waitingForConnectionTotal, waitSecondsHighCount]          
- JVMRuntime:
    key: name
    prefix: jvm_
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent, heapSizeMax, uptime, processCpuLoad]

- applicationRuntimes:
    key: applicationName
    workManagerRuntimes:
      key: name
      prefix: workmanager_
      values: [pendingRequests, completedRequests, stuckThreadCount]
        
- maxThreadsConstraintRuntimes:
    key: name
    prefix: max_threadsconstraint_
    values: [configuredCount, count, deferredRequests, executingRequests]

- minThreadsConstraintRuntimes:
    key: name
    prefix: min_threadsconstraint_
    values: [completedRequests, configuredCount, count, currentWaitTime, executingRequests, maxWaitTime]

**Comment by russgold** [comment]
You've also got duplicates of componentRuntimes; only the second will be used. 

I am having problems duplicating your problem.

**Comment by russgold** [comment]
The line numbers in the stack trace seem to match a very old version of the code. Can you pull the latest (as of a year ago), rebuild, and try again?

**Comment by russgold** [comment]
With no responses in five months, I assume that the problem is no longer present.
