### ISSUE TITLE
Fetch metrics over https

### ISSUE THREAD

**Issue by taelagab** [oracle/weblogic-monitoring-exporter#101]
I'm trying to get metrics over https like https://host:8251/wls-exporter/metrics. Is it supported ?
As, when I curl -k https://host:8251/wls-exporter -u user:pass it fetches the configuration but curl -k https://host:8251/wls-exporter/metrics throws error.
`t org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at io.prometheus.wls.rest.WebClientImpl.getReply(WebClientImpl.java:75)
        at io.prometheus.wls.rest.WebClientImpl.sendRequest(WebClientImpl.java:66)
        at io.prometheus.wls.rest.WebClientImpl.doPostRequest(WebClientImpl.java:96)
        at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:89)
        at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:67)
        at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:61)
        at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:54)
        at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:68)
        at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:44)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:247)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3702)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3672)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:328)
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1705)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1665)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:652)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused by: org.apache.http.ProtocolException: The server failed to respond with a valid HTTP response
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:149)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
`

**Comment by pascalBrand** [comment]
Hi, 
I had the same issue. I found some hardcoded http:// pattern in the code. I was able to use the code in https after changing those to https. But it doesn't work in http anymore of course.

Hope this helps,
Pascal

**Comment by taelagab** [comment]
Hey Pascal,
Could you point me to some of these hard coded sections?
Thanks

**Comment by pascalBrand** [comment]
Hi,

There are a few in different places. Here are those I changed:

weblogic-monitoring-exporter-1.1.2]$ find . -name "*.java" -exec grep https: {} \; -print
    public static final String RUNTIME_URL_PATTERN = "**https:**//%s:%d/management/weblogic/latest/serverRuntime/search";
    public static final String CONFIGURATION_URL_PATTERN = "**https:**//%s:%d/management/weblogic/latest/serverConfig/search";
./src/main/java/io/prometheus/wls/rest/domain/QueryType.java
    private static final String URL_PATTERN = "**https:**//%s:%d/management/weblogic/latest/serverRuntime/search";
./src/main/java/io/prometheus/wls/rest/LiveConfiguration.java
        assertThat(syncConfiguration.getUrl(), equalTo("**https:**//sync:8999/"));
            "query_sync:\n  url: **https**://sync:8999/\n  interval: 3";
        assertThat(syncConfiguration.getUrl(), equalTo("**https**://sync:8999/"));
            "query_sync:\n  url: **https**://sync:8999/\n";
./src/test/java/io/prometheus/wls/rest/domain/ExporterConfigTest.java
    private static final String UNDEFINED_HOST_URL = "**https**://undefined.invalid";
    private static final String UNDEFINED_PORT_URL = "**https:**//localhost:59236";
./src/test/java/io/prometheus/wls/rest/WebClientImplTest.java
    private static final String URL_PATTERN = "**https:**//%s:%d/management/weblogic/latest/serverRuntime/search";

It will work in https but not in http anymore.

Hope this helps,
Pascal

**Comment by russgold** [comment]
This seems important to fix. Thanks for reporting it,

**Comment by russgold** [comment]
Could you please try the support_https and let me know if it addresses the problem?

**Comment by russgold** [comment]
I am curious about the change you mention, as that is supposed to be the default behavior. You don't need to specify the REST port if the query goes directly to the server.

**Comment by pascalBrand** [comment]
Yes, when accessing the wls-exporter from Prometheus, it is the default behavior. But when accessing the wls-exporter webapp through Ingress server to load a new config or to check the metrics then the rest port is needed. This means a different war file for each WLS server as the config where the rest port is defined is included in it.
Can I send you or upload somewhere a zip file of the changed code for you to have a look ?
Pascal

**Comment by russgold** [comment]
Sure, you can email me (email in my profile) or create a pull request if the change is production-ready, including unit tests.

**Comment by zeeshantariqrafique** [comment]
Is this fixed in the master branch? As I still face error while hitting on https://host:port/exporter-webapp/metrics

Error is Caused by: java.security.cert.CertificateException: **No X509TrustManager implementation available**

**Comment by zeeshantariqrafique** [comment]
I am using the **_master_** branch which as far as I know is fixed for 'https'. However, I get below error when I hit https://localhost:8002/wls-exporter/metrics


Error 500--Internal Server Error

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1689)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.prometheus.wls.rest.WebClientImpl.getReply(WebClientImpl.java:73)
	at io.prometheus.wls.rest.WebClientImpl.sendRequest(WebClientImpl.java:64)
	at io.prometheus.wls.rest.WebClientImpl.doPostRequest(WebClientImpl.java:94)
	at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:92)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:62)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:55)
	at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:74)
	at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)

**Comment by russgold** [comment]
That seems to be a configuration issue with WebLogic.

**Comment by russgold** [comment]
Please try the master branch now. Make sure WLS is configured with key store and trust store.
