### ISSUE TITLE
master branch still not working with https

### ISSUE THREAD

**Issue by zeeshantariqrafique** [oracle/weblogic-monitoring-exporter#109]
I am using the master branch which as far as I know is fixed for 'https'. However, I get below error when I hit https://localhost:8002/wls-exporter/metrics

Error 500--Internal Server Error

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:198)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:331)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:325)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1689)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at io.prometheus.wls.rest.WebClientImpl.getReply(WebClientImpl.java:73)
at io.prometheus.wls.rest.WebClientImpl.sendRequest(WebClientImpl.java:64)
at io.prometheus.wls.rest.WebClientImpl.doPostRequest(WebClientImpl.java:94)
at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:92)
at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:68)
at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:62)
at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:55)
at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:74)
at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:45)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)

**Comment by russgold** [comment]
Looks as though this may be the issue and solution.

https://stackoverflow.com/questions/31372956/weblogic-javax-net-ssl-sslhandshakeexception

**Comment by zeeshantariqrafique** [comment]
This does not solve the problem, Now I get a 401 exception for invalid username when I do a curl request with my certificate 
For Example : curl -s -k certificate.p12:passphrase https://localhost:8080/wls-exporter .
I wish to use certificate and not a username and password.

**Comment by mriccell** [comment]
Closing this issue due to lack of feedback.  Filer has not responded in 2 weeks.  If  zeeshantariqrafique  or anyone else feels like this issue is still relevant to them, please respond here so that we can reopen this case.
