### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out causes com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by vkhanork** [oracle/weblogic-monitoring-exporter#120]
`
Root cause of
ServletException.
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
WatchRule: (log.severityString == 'Error') and ((log.messageId ==
'WL-101020') or (log.messageId == 'WL-101017') or (log.messageId ==
'WL-000802') or (log.messageId == 'BEA-101020') or (log.messageId ==
'BEA-101017') or (log.messageId == 'BEA-000802'))
WatchData: MESSAGE = [ServletContext@1005224623[app:wls-exporter
module:wls-exporter.war path:null spec-version:3.1]] Root cause of
ServletException.
com.google.gson.JsonSyntaxException:
com.google.gson.stream.MalformedJsonException: Use
JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path
$
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at
io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:1
85)
        at
io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:
181)
        ............
Caused By: com.google.gson.stream.MalformedJsonException: Use
JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path
$
        at
com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at
com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at
io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:1
85)
        at
io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:
181)
        at
io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:93)
`
Above exeception is generated, mostly caused by a request timing out. Is this issue known? Already fixed? Kindly confirm.

**Comment by ddsharpe** [comment]
We need to look into whether we can retry or handle socket timeouts more elegantly.

**Comment by linuxtechie** [comment]
@ddsharpe kindly confirm if this bug is being actively tracked ?

**Comment by ddsharpe** [comment]
Tracked internally as OWLS-95491.
