### ISSUE TITLE
wls-exporter/metrics page on browser reports java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set

### ISSUE THREAD

**Issue by ashron07** [oracle/weblogic-monitoring-exporter#125]
Hi,

I have deployed wls-exporter on a weblogic 12.2.1.4 domain running as Container on Docker 19.03.8.

Downloaded wls-exporter 1.2 from Github . Executed get1.2.0.sh script and packed config.yml in war pkg.

Deployed wls-exporter on Admin. I can access landing page without any issues which shows all configuration defined in config.yml file.

However,   when I try to access weblogic metrics via browser , it throws following exception.

<[ServletContext@1877579313[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.NoSuchMethodError: com.google.gson.JsonObject.keySet()Ljava/util/Set;
	at com.oracle.wls.exporter.domain.MetricsScraper.getValueNames(MetricsScraper.java:72)
	at com.oracle.wls.exporter.domain.MetricsScraper.scrapeItem(MetricsScraper.java:63)
	at com.oracle.wls.exporter.domain.MetricsScraper.scrape(MetricsScraper.java:42)
	at com.oracle.wls.exporter.domain.ExporterConfig.scrapeMetrics(ExporterConfig.java:88)
	at com.oracle.wls.exporter.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:172)
	at com.oracle.wls.exporter.ExporterServlet.getMetrics(ExporterServlet.java:111)
	at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:72)
	at com.oracle.wls.exporter.ExporterServlet.printMetrics(ExporterServlet.java:62)
	at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:55)
	at com.oracle.wls.exporter.PassThroughAuthenticationServlet.performRequest(PassThroughAuthenticationServlet.java:105)
	at com.oracle.wls.exporter.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:85)
	at com.oracle.wls.exporter.ExporterServlet.doGet(ExporterServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:250)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3793)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3763)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2451)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2299)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2277)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1720)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1680)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)

**Comment by igorid70** [comment]
Hi @ashron07 
Were you able to find the solution? I have exactly the same issue.

**Comment by russgold** [comment]
Have you tried running on a managed server? The exporter is not designed to run on the admin server.

I don't really understand why that would result in this error, so if it doesn't, can you run `jar tvf` against your WAR and past the result here?

**Comment by igorid70** [comment]
Hi
I am currently running the wls exporter implementation in a test environment where WLS is not clustered and consists of a single server which is also the admin.
Anyway, after the digging, I was able to find the reason - as it happens in many cases of java.lang.NoSuchMethodError exceptions, WL had another gson jar which was in conflict with the one packed in wls-exporter.war. After fixing it, the metrics are accessible

**Comment by ashron07** [comment]
Hi,

Thanks Russgold for your response.  

Yes, I am running WebLogic on Admin only and not clustered. It is on Docker platform as container. 

@igorid70 
Thanks. I think I also attempted with same approach of replacing gson however, I was getting same error. 

Appreciate if you can further describe the steps you have performed then I will compare and validate against mine. 

Thanks both of you.

**Comment by igorid70** [comment]
I just analyzed the classpath of Weblogic as it is shown by ps command and found that one of the elements of the classpath contained a folder with * (i.e. path1:path2:path3/lib/*). As no gson jar was directly added to the classpath, I checked all the locations where classpath is set with *. One of them included gson which I removed, so only gson.jar from wls exporter war was actually in use. Once done, all worked smoothly (almost :), I am still checking why deployment state is not presented for components when they fail to deploy - wls exporter does not list failed components at all as if they don't exist)

**Comment by ashron07** [comment]
@igorid70  @russgold 
Just to provide an update from my end.

By further analyzing configuration and logs , it seems that I have gson-2.3.jar included in the WebLogic class path which apparently seems to conflict with embedded version from wls exporter war which has gson 2.8 inside.

After I removed it, started the domain. Once completed,  it worked as expected with no error.

Thank you once again to  both of you for your support and assistance.

**Comment by russgold** [comment]
And thanks to both of you for finding that. I am going to see what I can do to have the exporter detect the problem so that it can at least provide a more useful error message.
