### ISSUE TITLE
Error 500 at  /wls-exporter/metrics

### ISSUE THREAD

**Issue by katerinalampidou** [oracle/weblogic-monitoring-exporter#139]
i am using get1.3.0.sh and a sample config file.
weblogic version is 12.2.1.3 development mode and the exporter is deployed on the managed server.

I can see the initial page /wls-exporter correctly , but when I try to access /wls-exporter/metrics I get following error: 

java.lang.BootstrapMethodError: call site initialization exception
	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at com.oracle.wls.exporter.WebClientImpl$HttpResponseImpl.getHeadersAsStream(WebClientImpl.java:123)
	at com.oracle.wls.exporter.WebClientCommon.getAuthenticationHeader(WebClientCommon.java:194)
	at com.oracle.wls.exporter.WebClientCommon.createAuthenticationChallengeException(WebClientCommon.java:190)
	at com.oracle.wls.exporter.WebClientCommon.processStatusCode(WebClientCommon.java:155)
	at com.oracle.wls.exporter.WebClientCommon.getReply(WebClientCommon.java:144)
	at com.oracle.wls.exporter.WebClientCommon.sendRequest(WebClientCommon.java:135)
	at com.oracle.wls.exporter.WebClientCommon.doPostRequest(WebClientCommon.java:123)
	at com.oracle.wls.exporter.WebClientImpl.doPostRequest(WebClientImpl.java:47)
	at com.oracle.wls.exporter.ExporterServlet.requestMetrics(ExporterServlet.java:116)
	at com.oracle.wls.exporter.ExporterServlet.getMetrics(ExporterServlet.java:108)
	at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:72)
	at com.oracle.wls.exporter.ExporterServlet.printMetrics(ExporterServlet.java:62)
	at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:55)
	at com.oracle.wls.exporter.PassThroughAuthenticationServlet.performRequest(PassThroughAuthenticationServlet.java:111)
	at com.oracle.wls.exporter.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:91)
	at com.oracle.wls.exporter.ExporterServlet.doGet(ExporterServlet.java:45)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:247)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3697)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3667)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1703)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1663)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)

Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	... 44 more

**Comment by russgold** [comment]
OK, this is very odd. From your stack trace I see:
```
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair
at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
```

And when I look at the Header class, I see:
```
package org.apache.http;

   :
   : (comments, etc.)
   
public interface Header extends NameValuePair {
```

So that error is stating the opposite of what appears to be true. Can you describe your environment in detail (OS, JDK, anything else that might be relevant)?

**Comment by katerinalampidou** [comment]
The domain is running in Kubernetes on a minikube (i suppose the specs of the VM are irrelevant)

My image is based on the sample of the weblogic kubernetes operator, so it is based on domain-home-in-image:12.2.1.3.0.
java version "1.8.0_271"
operator version 3.1.2
K8s v1.20.0

I only chose operator and k8s version at the beginning of the setup. the rest is part of the image.

**Comment by russgold** [comment]
I cannot say that I have ever tried running this on minikube. Does it fail the same way if you run in a full Kubernetes install, or outside of Kubernetes?

**Comment by mriccell** [comment]
Closing this issue due to lack of feedback.  Filer has not responded in 2 weeks.  If katerinalampidou  or anyone else feels like this issue is still relevant to them, please respond here so that we can reopen this case.
