### ISSUE TITLE
error 500 malformed JSON 

### ISSUE THREAD

**Issue by tmpjg** [oracle/weblogic-monitoring-exporter#147]
Hi!
I am getting the following error using version 1.2.0 and weblogic 12.1.3.0.0 on /wls-exporter/metrics . 

```
####<12-abr-2021 19H52' CEST> <Error> <HTTP> <servername> <servername> <[ACTIVE] ExecuteThread: '4' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <2f76ce4d-3c07-4610-b7ba-c343e19a1ca3-00005f92> <1618249956848> <BEA-101020> <[ServletContext@970282064[app:wls-exporter module:wls-exporter.war path:null spec-version:3.0]] Servlet failed with an Exception
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.oracle.wls.exporter.LiveConfiguration.toJsonObject(LiveConfiguration.java:176)
        at com.oracle.wls.exporter.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:172)
        at com.oracle.wls.exporter.ExporterServlet.getMetrics(ExporterServlet.java:111)
        at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:72)
        at com.oracle.wls.exporter.ExporterServlet.printMetrics(ExporterServlet.java:62)
        at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:55)
        at com.oracle.wls.exporter.PassThroughAuthenticationServlet.performRequest(PassThroughAuthenticationServlet.java:105)
        at com.oracle.wls.exporter.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:85)
        at com.oracle.wls.exporter.ExporterServlet.doGet(ExporterServlet.java:45)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3427)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3397)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1621)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
Caused By: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at com.oracle.wls.exporter.LiveConfiguration.toJsonObject(LiveConfiguration.java:176)
        at com.oracle.wls.exporter.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:172)
        at com.oracle.wls.exporter.ExporterServlet.getMetrics(ExporterServlet.java:111)
        at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:72)
        at com.oracle.wls.exporter.ExporterServlet.printMetrics(ExporterServlet.java:62)
        at com.oracle.wls.exporter.ExporterServlet.displayMetrics(ExporterServlet.java:55)
        at com.oracle.wls.exporter.PassThroughAuthenticationServlet.performRequest(PassThroughAuthenticationServlet.java:105)
        at com.oracle.wls.exporter.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:85)
        at com.oracle.wls.exporter.ExporterServlet.doGet(ExporterServlet.java:45)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3427)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3397)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1621)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
```

I clarify that I do not use newer versions because when trying to install them weblogic gives the error: 
```
Message icon - Error Unable to access the selected application.
Message icon - Error java.io.IOException
Message icon - Error weblogic.utils.compiler.ToolFailureException
```

**Comment by mriccell** [comment]
The Monitoring Exporter is supported on WebLogic Server version 12.2.1 or later.  You seem to be testing on unsopported versions.
