### ISSUE TITLE
Exception raised during server startup

### ISSUE THREAD

**Issue by echocharlie125** [oracle/weblogic-monitoring-exporter#18]
The following exception is raised during WebLogic server startup, in the standard output : 
<Apr 12, 2019 9:29:18,706 AM CEST> <Error> <HTTP> <BEA-101020> <[ServletContext@1626013322[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1]] Servlet failed with an Exception
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.google.gson.JsonParser.parse(JsonParser.java:45)
        at io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:145)
        at io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:141)
        at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:84)
        Truncated. see log file for complete stacktrace
Caused By: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        Truncated. see log file for complete stacktrace
>

Here is the config.yml file embeded in the war file : 
metricsNameSnakeCase: true
queries:
- ThreadPoolRuntime:
    key: name
    prefix: threadpool_
    values: [executeThreadTotalCount, throughput, hoggingThreadCount, standbyThreadCount, executeThreads, executeThreadIdleCount]

- applicationRuntimes:
    key: name
    workManagerRuntimes:
      prefix: workmanager_
      key: applicationName

**Comment by russgold** [comment]
I am unable to duplicate this. What version of WLS are you using? Can you try the latest exporter? I've made some fixes.

**Comment by echocharlie125** [comment]
Unable to reproduce the issue anymore, you can close it i think. Thanks for other fixes.
