### ISSUE TITLE
com.google.gson.JsonArray error

### ISSUE THREAD

**Issue by cetin2023** [oracle/weblogic-monitoring-exporter#276]
I deployed the war file and when I tried to access to the metrics in wls-exporter/metrics, I got that error:

WLS:12.2.1.4
jdk: 1.8

By the way I've been using wls-exporter in different wls domain on the same machine.

<BEA-101017> <[ServletContext@273816737[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
	at com.oracle.wls.exporter.domain.JsonQuerySpec.asStringArray(JsonQuerySpec.java:80)
	at com.oracle.wls.exporter.domain.JsonQuerySpec.toJsonObject(JsonQuerySpec.java:70)
	at com.oracle.wls.exporter.domain.JsonQuerySpec.toJson(JsonQuerySpec.java:63)
	at com.oracle.wls.exporter.domain.MBeanSelector.getRequest(MBeanSelector.java:348)
	at com.oracle.wls.exporter.ExporterCall.requestMetrics(ExporterCall.java:95)
	at com.oracle.wls.exporter.ExporterCall.getMetrics(ExporterCall.java:85)
	at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:51)
	at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:41)
	at com.oracle.wls.exporter.ExporterCall.invoke(ExporterCall.java:33)
	at com.oracle.wls.exporter.AuthenticatedCall.performRequest(AuthenticatedCall.java:188)
	at com.oracle.wls.exporter.AuthenticatedCall.doWithAuthentication(AuthenticatedCall.java:144)
	at com.oracle.wls.exporter.webapp.ExporterServlet.doGet(ExporterServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.security.jps.ee.http.JpsAbsFilter$3.run(JpsAbsFilter.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.security.jps.util.JpsSubject.doAsPrivileged(JpsSubject.java:314)
	at oracle.security.jps.ee.util.JpsPlatformUtil.runJaasMode(JpsPlatformUtil.java:650)
	at oracle.security.jps.ee.http.JpsAbsFilter.runJaasMode(JpsAbsFilter.java:112)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilterInternal(JpsAbsFilter.java:293)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilter(JpsAbsFilter.java:150)
	at oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:94)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:248)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.jrf.servlet.ExtensibleGlobalFilter.doFilter(ExtensibleGlobalFilter.java:92)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3800)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3766)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2454)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2302)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2280)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1721)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1681)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused By: java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
	at com.oracle.wls.exporter.domain.JsonQuerySpec.asStringArray(JsonQuerySpec.java:80)
	at com.oracle.wls.exporter.domain.JsonQuerySpec.toJsonObject(JsonQuerySpec.java:70)
	at com.oracle.wls.exporter.domain.JsonQuerySpec.toJson(JsonQuerySpec.java:63)
	at com.oracle.wls.exporter.domain.MBeanSelector.getRequest(MBeanSelector.java:348)
	at com.oracle.wls.exporter.ExporterCall.requestMetrics(ExporterCall.java:95)
	at com.oracle.wls.exporter.ExporterCall.getMetrics(ExporterCall.java:85)
	at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:51)
	at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:41)
	at com.oracle.wls.exporter.ExporterCall.invoke(ExporterCall.java:33)
	at com.oracle.wls.exporter.AuthenticatedCall.performRequest(AuthenticatedCall.java:188)
	at com.oracle.wls.exporter.AuthenticatedCall.doWithAuthentication(AuthenticatedCall.java:144)
	at com.oracle.wls.exporter.webapp.ExporterServlet.doGet(ExporterServlet.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:295)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:353)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.security.jps.ee.http.JpsAbsFilter$3.run(JpsAbsFilter.java:175)
	at java.security.AccessController.doPrivileged(Native Method)
	at oracle.security.jps.util.JpsSubject.doAsPrivileged(JpsSubject.java:314)
	at oracle.security.jps.ee.util.JpsPlatformUtil.runJaasMode(JpsPlatformUtil.java:650)
	at oracle.security.jps.ee.http.JpsAbsFilter.runJaasMode(JpsAbsFilter.java:112)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilterInternal(JpsAbsFilter.java:293)
	at oracle.security.jps.ee.http.JpsAbsFilter.doFilter(JpsAbsFilter.java:150)
	at oracle.security.jps.ee.http.JpsFilter.doFilter(JpsFilter.java:94)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.dms.servlet.DMSServletFilter.doFilter(DMSServletFilter.java:248)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at oracle.jrf.servlet.ExtensibleGlobalFilter.doFilter(ExtensibleGlobalFilter.java:92)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3800)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3766)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2454)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2302)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2280)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1721)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1681)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)

**Comment by cetin2023** [comment]
I checked it and there is an application that using older version of gson and it has to use the older one. Now how could I solve it? there are some solution like it need to put json_xxx.jar to the wls_exporter.war but I don't know how It does. Do you have any solution offer?

**Comment by russgold** [comment]
OK, I see that I am calling methods added in version 2.4. What is your old version of GSon? I will try to restrict the code to use methods defined there.

**Comment by cetin2023** [comment]
Hi Russgold,

We use gson-2.2.4.jar under ${DOMAIN_HOME}/lib folder. Unfortunately we don't have a chance to change it because of we don't get a support for it and when I change gson with newer version like 2.8.1, It's causing different problems. Can I add gson.2.8.1 into the wls-exporter?

**Comment by russgold** [comment]
The exporter ships with son 2.10.1 because our internal standards are to use the latest working version of third-party libraries. But I have learned of another approach that might solve this. 

https://docs.oracle.com/cd/E11035_01/wls100/programming/classloading.html#wp1097187

It appears that you can tell a web app to use alternative versions of libraries. So I am going to try to reproduce your issue and then see if the above works. You might want to try it yourself.

**Comment by russgold** [comment]
The change is in branch owls-109276.

**Comment by cetin2023** [comment]
It works! :) Thank you so much.
