### ISSUE TITLE
Error 500 on wls-exporter/metrics

### ISSUE THREAD

**Issue by dasutera** [oracle/weblogic-monitoring-exporter#28]
Hi when I click on metrics uri "/wls-exporter/metrics"  I get the error 500

by setup enviroment :

Weblogic Version  12.2.1.1.0 Thu Jun  2 16:21:58 PDT 2016 1784838
Java Version: 1.8.0_77

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 11 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:179)
	at io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:175)
	at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:84)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:62)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:55)
	at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:45) 

the same application instead works on another installation of Weblogic 12.2.1.0.0 but with java version different 1.8.0_201

thanks in advantage 

Add that Rest API is enable on Weblogic Domain Configuration

magement/tenant-monitoring/servers 

body 

    items 
            name AdminServer
            state RUNNING
            health HEALTH_OK
            name visitorservices_server1
            state SHUTDOWN
            name sitecapture_server1
            state SHUTDOWN
            name wcsites_server1
            state RUNNING
            health HEALTH_OK

**Comment by russgold** [comment]
I have created a branch, issue28_test, which adds a diagnostic. Please try it and let me see the equivalent error message.

**Comment by dasutera** [comment]
[error_issue28.txt](https://github.com/oracle/weblogic-monitoring-exporter/files/3236075/error_issue28.txt)

I have attached the error dump

**Comment by russgold** [comment]
Thanks; the exporter appears to be generating a bad query. What does your exporter configuration look like? That is, what does "/wls-exporter" show?

**Comment by dasutera** [comment]
show this

This is the WebLogic Monitoring Exporter.

The metrics are found at metrics relative to this location.
Configuration

To change the configuration:
Append Replace

Current Configuration

host: 192.168.155.75
port: 7001
metricsNameSnakeCase: true
queries:
- key: name
  keyName: server
  JVMRuntime:
    prefix: jvm_
    key: name
    values: [heapFreeCurrent, heapFreePercent, heapSizeCurrent]

**Comment by russgold** [comment]
I don't see the additional debug information I added in branch issue28_test. Did you use that branch to install the exporter?

**Comment by dasutera** [comment]
do you refer to the WLs diagnostic file? 

[2019-05-10T13:43:27.254+02:00] [AdminServer] [NOTIFICATION] [JPS-00202] [oracle.jps.common] [tid: [STANDBY].ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <WLS Kernel>] [ecid: 564eef76-8df5-438d-95fa-0f4184d81d87-00000009,0] [partition-name: DOMAIN] [tenant-name: GLOBAL] Jps post service activation operations started.
[2019-05-29T17:03:52.828+02:00] [AdminServer] [NOTIFICATION] [DFW-40101] [oracle.dfw.incident] [tid: [ACTIVE].ExecuteThread: '57' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <WLS Kernel>] [ecid: 564eef76-8df5-438d-95fa-0f4184d81d87-00001d4b,0] [partition-name: DOMAIN] [tenant-name: GLOBAL] An incident has been signalled with the incident facts: [problemKey=DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter] incidentSource=SYSTEM incidentTime=Wed May 29 17:03:52 CEST 2019 errorMessage=DFW-99998 executionContextId=564eef76-8df5-438d-95fa-0f4184d81d87-00001d48]
[2019-05-29T17:03:56.548+02:00] [AdminServer] [INCIDENT_ERROR] [DFW-40104] [oracle.dfw.incident] [tid: [ACTIVE].ExecuteThread: '57' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <WLS Kernel>] [ecid: 564eef76-8df5-438d-95fa-0f4184d81d87-00001d4b,0] [errid: 1] [detailLoc: /opt/wcs/user_projects/domains/wcs/servers/AdminServer/adr/diag/ofm/wcs/AdminServer/incident/incdir_1] [probKey: DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter]] [partition-name: DOMAIN] [tenant-name: GLOBAL] incident 1 created with problem key "DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter]"
[2019-05-31T14:50:55.420+02:00] [AdminServer] [NOTIFICATION] [DFW-40101] [oracle.dfw.incident] [tid: [ACTIVE].ExecuteThread: '22' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <WLS Kernel>] [ecid: 564eef76-8df5-438d-95fa-0f4184d81d87-0000201a,0] [partition-name: DOMAIN] [tenant-name: GLOBAL] An incident has been signalled with the incident facts: [problemKey=DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter] incidentSource=SYSTEM incidentTime=Fri May 31 14:50:55 CEST 2019 errorMessage=DFW-99998 executionContextId=564eef76-8df5-438d-95fa-0f4184d81d87-00002017]
[2019-05-31T14:50:57.624+02:00] [AdminServer] [INCIDENT_ERROR] [DFW-40104] [oracle.dfw.incident] [tid: [ACTIVE].ExecuteThread: '22' for queue: 'weblogic.kernel.Default (self-tuning)'] [userId: <WLS Kernel>] [ecid: 564eef76-8df5-438d-95fa-0f4184d81d87-0000201a,0] [errid: 2] [detailLoc: /opt/wcs/user_projects/domains/wcs/servers/AdminServer/adr/diag/ofm/wcs/AdminServer/incident/incdir_2] [probKey: DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter]] [partition-name: DOMAIN] [tenant-name: GLOBAL] incident 2 created with problem key "DFW-99998 [com.google.gson.stream.MalformedJsonException][oracle.security.jps.ee.http.JpsAbsFilter$1.run][wls-exporter]"

**Comment by dasutera** [comment]
Yes i have use this command : 

git clone --single-branch -b issue28_test https://github.com/oracle/weblogic-monitoring-exporter.git
cd weblogic-monitoring-exporter
mvn install
cd webapp
mvn package
after these commands on the directory target 
i found wls-exporter.war, that I installed on WLS

**Comment by russgold** [comment]
The error_issue28.txt file you uploaded includes the following partial stack trace:

```
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:179)
	at io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:175)
```

But in the issue28_test branch, the call from toJsonObject to JsonParser.parse is at line 187. Given this stack trace, your WAR appears to have been built with version e16d6c4663a5fc6402a47ed1ce May 22 . Can you please try again? Try deleting the WAR to make sure you are using a new version.

**Comment by russgold** [comment]
No response in 15 days; I am assuming that the problem is fixed by using the latest code.
