### ISSUE TITLE
Error 500--Internal Server Error

### ISSUE THREAD

**Issue by sstglobal** [oracle/weblogic-monitoring-exporter#424]
Hello everyone,

I encountered an issue when trying to access host:/wls-exporter/metrics.

Here is the log that I found on the server. Does anyone else have a similar issue and know how to fix it? Please help me. Many thanks in advance!

`####<May 6, 2024 1:07:19,146 PM EEST> <Error> <HTTP> <ubtest> <AdminServer> <[ACTIVE] ExecuteThread: '31' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <4d31f96a-5eb7-4f0c-8404-9d3881784452-00000092> <1714990039146> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-101017> <[ServletContext@539231249[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1]] Root cause of ServletException.
java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.conn.ssl.SSLConnectionSocketFactory
        at com.oracle.wls.exporter.WebClientImpl$SelfSignedCertificateAcceptor.createSSLConnectionSocketFactory(WebClientImpl.java:198)
        at com.oracle.wls.exporter.WebClientImpl$SelfSignedCertificateAcceptor.<init>(WebClientImpl.java:185)
        at com.oracle.wls.exporter.WebClientImpl$ApacheHttpClient.<init>(WebClientImpl.java:140)
        at com.oracle.wls.exporter.WebClientImpl.createClientExec(WebClientImpl.java:134)
        at com.oracle.wls.exporter.WebClientCommon.sendRequest(WebClientCommon.java:132)
        at com.oracle.wls.exporter.WebClientCommon.doPostRequest(WebClientCommon.java:121)
        at com.oracle.wls.exporter.ExporterCall.requestMetrics(ExporterCall.java:95)
        at com.oracle.wls.exporter.ExporterCall.getMetrics(ExporterCall.java:85)
        at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:51)
        at com.oracle.wls.exporter.ExporterCall.displayMetrics(ExporterCall.java:41)
        at com.oracle.wls.exporter.ExporterCall.invoke(ExporterCall.java:33)
        at com.oracle.wls.exporter.AuthenticatedCall.performRequest(AuthenticatedCall.java:188)
        at com.oracle.wls.exporter.AuthenticatedCall.doWithAuthentication(AuthenticatedCall.java:144)
        at com.oracle.wls.exporter.webapp.ExporterServlet.doGet(ExporterServlet.java:47)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:247)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3697)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3667)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1703)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1663)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)`

**Comment by lennyphan** [comment]
Have not seen the issue.  Can you provide information on how to replicate it?
