### ISSUE TITLE
Exception from wls-exporter

### ISSUE THREAD

**Issue by rrpai** [oracle/weblogic-monitoring-exporter#76]
Exception from wls-exporter

- we use prometheus to scrape the wls servers for metrics

- we see this exception repeatedly in one of wls servers in a production instance. So metrics is not exported from this server 

- after we restarted this wls, issue went away

- it looks like a bug.  Please comment

```

####<Dec 12, 2019 6:02:46,947 AM UTC> <Error> <HTTP> <cec-server-1.cec-server.cec-wls.svc.cluster.local> <cec_server_1> <[ACTIVE] ExecuteThread: '42' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <7fb21a40-36e7-4bb2-bb2b-f594af1e1ab0-0012a655> <1576130566947> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-101017> <[ServletContext@597897861[app:wls-exporter module:wls-exporter.war path:null spec-version:3.1]] Root cause of ServletException.
java.util.NoSuchElementException
    at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
    at java.util.ArrayDeque.remove(ArrayDeque.java:452)
    at io.prometheus.wls.rest.MessagesServlet.addExchange(MessagesServlet.java:44)
    at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:90)
    at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:67)
    at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:61)
    at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:54)
    at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:68)
    at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:44)

```

**Comment by russgold** [comment]
How do I duplicate this?

**Comment by rrpai** [comment]
- We dont know how to reproduce this as it happened in production instance without any specific reason

**Comment by nathan-vp** [comment]
We also see this happening on a semi-regular basis. No clue how to reproduce it, it happens without apparent reason.

**Comment by mriccell** [comment]
Closing due to lack of activity
