### ISSUE TITLE
MalformedJsonException

### ISSUE THREAD

**Issue by darekbola** [oracle/weblogic-monitoring-exporter#85]
Hi!

I am facing issues with wls-exporter. I am getting error when I am checking metrics after uploading queries:
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at io.prometheus.wls.rest.LiveConfiguration.toJsonObject(LiveConfiguration.java:185)
	at io.prometheus.wls.rest.LiveConfiguration.scrapeMetrics(LiveConfiguration.java:181)
	at io.prometheus.wls.rest.ExporterServlet.getMetrics(ExporterServlet.java:93)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:67)
	at io.prometheus.wls.rest.ExporterServlet.printMetrics(ExporterServlet.java:61)
	at io.prometheus.wls.rest.ExporterServlet.displayMetrics(ExporterServlet.java:54)
	at io.prometheus.wls.rest.ExporterServlet$$Lambda$15/1484816377.execute(Unknown Source)
	at io.prometheus.wls.rest.PassThroughAuthenticationServlet.doWithAuthentication(PassThroughAuthenticationServlet.java:68)
	at io.prometheus.wls.rest.ExporterServlet.doGet(ExporterServlet.java:44)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:346)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:243)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3447)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3417)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 29 more

My weblogic version: WebLogic Server Version: 12.1.3.0.0
My configuration: 
metricsNameSnakeCase: true
queries:
- JVMRuntimeMBean:
   key: name
   prefix: jvm_
   values: [HeapFreeCurrent, HeapFreePercent, HeapSizeCurrent, HeapSizeMax, Uptime]

What I see in weblogic monitoring dash board:
![image](https://user-images.githubusercontent.com/34620027/76505251-70700080-6449-11ea-8b4f-961b3309eccb.png)

![image](https://user-images.githubusercontent.com/34620027/76505291-8251a380-6449-11ea-9d36-af198a54d0ee.png)

This is a simple configuration just to test if this working.
I have seen that peoples have similar problem...
I bet this is problem with my yaml file configuration. Could you please help me?

Thank you in advance!

**Comment by darekbola** [comment]
I also tried:
metricsNameSnakeCase: true
queries:
- key: name
  keyName: server
  JVMRuntime:
    prefix: jvm_
    key: name
    values: [HeapFreeCurrent, HeapFreePercent, HeapSizeCurrent]

and

metricsNameSnakeCase: true
queries:
- key: name
  keyName: server
  JVMRuntimeMBean:
    prefix: jvm_
    key: name
    values: [HeapFreeCurrent, HeapFreePercent, HeapSizeCurrent]

**Comment by darekbola** [comment]
Lets close the issue. I have wrong version of weblogic :)
